# numpy -continued
## stacking, reshaping
Say that we have two np.arrays of identical length with one axis each and want to combine them
There are really three possible ways to do that: `vstack`, `hstack`, `dstack`.

In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-4, -5, -6], [-7, -8, -9]])
print(np.vstack((A, B)))
print(np.hstack((A, B)))
print(np.dstack((A, B)))

[[ 1  2  3]
 [ 4  5  6]
 [-4 -5 -6]
 [-7 -8 -9]]
[[ 1  2  3 -4 -5 -6]
 [ 4  5  6 -7 -8 -9]]
[[[ 1 -4]
  [ 2 -5]
  [ 3 -6]]

 [[ 4 -7]
  [ 5 -8]
  [ 6 -9]]]


Another operation is to *reshape* an array, for instance:

In [2]:
A = [[1, 2, 3], [4, 5, 6]]
print(A)
print(np.reshape(A, (6, 1)))
print(np.reshape(A, (6)))
print(np.reshape(A, (3, 2)))

[[1, 2, 3], [4, 5, 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(np.reshape(A, (4,5)))

ValueError: cannot reshape array of size 6 into shape (4,5)

## Example: managing grades

Let's pretend that we have stored student grades in two different nparray, one for assignments and the other for exams.
`assignments` consists of $n$ rows, each with the student ID, and 5 assignment marks
`exams` $n$ rows, each with the student ID, and 3 assignment marks.

* we can merge these two tables into a full grade list using `hstack`
* We could add records using `vstack`


In [5]:
# We'll explain how we read this from a file later
assignments  = np.loadtxt('grades.csv',delimiter = ',', skiprows= 1, usecols=(2, 4, 5, 6), max_rows=10)
exams        = np.loadtxt('grades.csv',delimiter = ',', skiprows= 1, usecols=(2, 7, 8, 9), max_rows=10)
print(assignments)
print(exams)

[[6.20565656e+08 7.70000000e+01 8.20000000e+01 9.10000000e+01]
 [1.07856531e+08 7.60000000e+01 8.70000000e+01 9.00000000e+01]
 [7.94394400e+06 7.90000000e+01 8.50000000e+01 9.20000000e+01]
 [1.14037001e+08 7.50000000e+01 7.80000000e+01 8.80000000e+01]
 [5.81943811e+08 7.60000000e+01 9.10000000e+01 9.80000000e+01]
 [3.67541502e+08 7.00000000e+01 8.40000000e+01 9.10000000e+01]
 [6.02646616e+08 8.10000000e+01 9.00000000e+01 8.60000000e+01]
 [2.82046779e+08 7.50000000e+01 9.00000000e+01 9.00000000e+01]
 [9.61460380e+08 7.50000000e+01 9.10000000e+01 9.10000000e+01]
 [5.27925346e+08 7.00000000e+01 8.90000000e+01 9.30000000e+01]]
[[6.20565656e+08 8.80000000e+01 7.80000000e+01 9.10000000e+01]
 [1.07856531e+08 9.00000000e+01 6.70000000e+01 8.80000000e+01]
 [7.94394400e+06 7.60000000e+01 6.00000000e+01 8.70000000e+01]
 [1.14037001e+08 9.00000000e+01 6.70000000e+01 8.40000000e+01]
 [5.81943811e+08 9.60000000e+01 5.60000000e+01 8.10000000e+01]
 [3.67541502e+08 9.10000000e+01 5.90000000e+01 9.50000

In [6]:
# Merging the arrays
allGrades = np.hstack((assignments, exams[:,1:]))
print(allGrades[:5,:])

[[6.20565656e+08 7.70000000e+01 8.20000000e+01 9.10000000e+01
  8.80000000e+01 7.80000000e+01 9.10000000e+01]
 [1.07856531e+08 7.60000000e+01 8.70000000e+01 9.00000000e+01
  9.00000000e+01 6.70000000e+01 8.80000000e+01]
 [7.94394400e+06 7.90000000e+01 8.50000000e+01 9.20000000e+01
  7.60000000e+01 6.00000000e+01 8.70000000e+01]
 [1.14037001e+08 7.50000000e+01 7.80000000e+01 8.80000000e+01
  9.00000000e+01 6.70000000e+01 8.40000000e+01]
 [5.81943811e+08 7.60000000e+01 9.10000000e+01 9.80000000e+01
  9.60000000e+01 5.60000000e+01 8.10000000e+01]]


In [7]:
# Adding the records for a new student
newRow = [123456789, 85, 90, 95, 80, 85, 80]
allGrades = np.vstack( (allGrades, newRow) )
for row in allGrades:
    print(f'ID: {int(row[0])}, grades: {row[1:]}')

ID: 620565656, grades: [77. 82. 91. 88. 78. 91.]
ID: 107856531, grades: [76. 87. 90. 90. 67. 88.]
ID: 7943944, grades: [79. 85. 92. 76. 60. 87.]
ID: 114037001, grades: [75. 78. 88. 90. 67. 84.]
ID: 581943811, grades: [76. 91. 98. 96. 56. 81.]
ID: 367541502, grades: [70. 84. 91. 91. 59. 95.]
ID: 602646616, grades: [81. 90. 86. 90. 76. 92.]
ID: 282046779, grades: [75. 90. 90. 85. 70. 89.]
ID: 961460380, grades: [75. 91. 91. 97. 53. 91.]
ID: 527925346, grades: [70. 89. 93. 94. 66. 90.]
ID: 123456789, grades: [85. 90. 95. 80. 85. 80.]


In [8]:
# Adding a new column with the final grade given as
# F = (A1 + np.array(A2 + A3) / 3 * 0.25 + (E1 + E2 + E3) / 3 * .75)
finalGrade = np.array([ np.average(row[1:4]) * .25 + np.average(row[4:7]) * .75 for row in allGrades])
print(finalGrade)

# finalGrades is a 'row' vector, so we need to reshape it iw we want to add it to our list of grades
numGrades = len(finalGrade)
# np.transpose(finalGrade)
np.hstack( (allGrades, np.reshape(finalGrade, (numGrades,1) )))


[85.08333333 82.33333333 77.08333333 80.33333333 80.33333333 81.66666667
 85.91666667 82.25       81.66666667 83.5        83.75      ]


array([[6.20565656e+08, 7.70000000e+01, 8.20000000e+01, 9.10000000e+01,
        8.80000000e+01, 7.80000000e+01, 9.10000000e+01, 8.50833333e+01],
       [1.07856531e+08, 7.60000000e+01, 8.70000000e+01, 9.00000000e+01,
        9.00000000e+01, 6.70000000e+01, 8.80000000e+01, 8.23333333e+01],
       [7.94394400e+06, 7.90000000e+01, 8.50000000e+01, 9.20000000e+01,
        7.60000000e+01, 6.00000000e+01, 8.70000000e+01, 7.70833333e+01],
       [1.14037001e+08, 7.50000000e+01, 7.80000000e+01, 8.80000000e+01,
        9.00000000e+01, 6.70000000e+01, 8.40000000e+01, 8.03333333e+01],
       [5.81943811e+08, 7.60000000e+01, 9.10000000e+01, 9.80000000e+01,
        9.60000000e+01, 5.60000000e+01, 8.10000000e+01, 8.03333333e+01],
       [3.67541502e+08, 7.00000000e+01, 8.40000000e+01, 9.10000000e+01,
        9.10000000e+01, 5.90000000e+01, 9.50000000e+01, 8.16666667e+01],
       [6.02646616e+08, 8.10000000e+01, 9.00000000e+01, 8.60000000e+01,
        9.00000000e+01, 7.60000000e+01, 9.20000000e+01, 8.

## Masking / filtering

Boolean operations on a np.array lead to np.arrays of booleans of the same size (this is consistent with the fact that numpy really want to do everything component-wise)
 

In [9]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(A)
print(A%2==0)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


Recall that True is 1 and False is 0

In [12]:
# Set all odd entries to 0
print(A*(A%2==0))

# Goal is to leave all even entries alone
# Make all odd entries even, by scaling by 2
print(A*(A%2==0)+2*A*(A%2 != 0))

[[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]]
[[ 2  2  6  4]
 [10  6 14  8]
 [18 10 22 12]]


In [14]:
print(A[A%2==0])
A[A%2 == 0] += 1
print(A)

[ 2  4  6  8 10 12]
[[ 1  3  3  5]
 [ 5  7  7  9]
 [ 9 11 11 13]]


In [15]:
# Back to the grades example: print a list of tte ID of all students with a 83% or above
mask = allGrades[:,-1]>83
print(mask)
print(allGrades[mask,:])



[ True  True  True  True False  True  True  True  True  True False]
[[6.20565656e+08 7.70000000e+01 8.20000000e+01 9.10000000e+01
  8.80000000e+01 7.80000000e+01 9.10000000e+01]
 [1.07856531e+08 7.60000000e+01 8.70000000e+01 9.00000000e+01
  9.00000000e+01 6.70000000e+01 8.80000000e+01]
 [7.94394400e+06 7.90000000e+01 8.50000000e+01 9.20000000e+01
  7.60000000e+01 6.00000000e+01 8.70000000e+01]
 [1.14037001e+08 7.50000000e+01 7.80000000e+01 8.80000000e+01
  9.00000000e+01 6.70000000e+01 8.40000000e+01]
 [3.67541502e+08 7.00000000e+01 8.40000000e+01 9.10000000e+01
  9.10000000e+01 5.90000000e+01 9.50000000e+01]
 [6.02646616e+08 8.10000000e+01 9.00000000e+01 8.60000000e+01
  9.00000000e+01 7.60000000e+01 9.20000000e+01]
 [2.82046779e+08 7.50000000e+01 9.00000000e+01 9.00000000e+01
  8.50000000e+01 7.00000000e+01 8.90000000e+01]
 [9.61460380e+08 7.50000000e+01 9.10000000e+01 9.10000000e+01
  9.70000000e+01 5.30000000e+01 9.10000000e+01]
 [5.27925346e+08 7.00000000e+01 8.90000000e+01 9.300

In [16]:
# Print only the student number and final grade
cols = [True,] +  [False,] * 6 + [True,]
print(allGrades[mask][:,cols])

IndexError: boolean index did not match indexed array along axis 1; size of axis is 7 but size of corresponding boolean axis is 8

## Masking Example

Weather data over a year

In [18]:
days = np.arange(365)
temp = 4 + 20*np.sin(2*np.pi*(days - 100)/365) + np.random.normal(0, 3, 365)
print(temp)

[-19.77119315 -20.42778333 -16.24514305 -17.36886693 -13.31975511
 -17.10008452 -19.99790636 -17.49717873 -14.51069657 -17.78623757
 -16.37143296 -13.80811967 -16.37408629 -16.1107595  -15.50238733
 -13.32932872 -16.84611636 -18.15752647 -20.06805176  -9.71699026
 -20.70323076 -10.06983302 -10.75584753 -19.83555259 -15.92749522
 -14.32211516 -15.57562871 -16.84687773 -14.37895641 -18.31036865
 -16.87897547  -8.14720137 -10.80502509 -16.80285531 -14.75021453
 -13.9284445  -13.28268534 -15.28597945 -14.35159715 -11.48735509
 -13.03833108 -12.40952735 -10.78790741 -15.30458848 -12.91308867
 -13.22346524 -11.45301854  -8.09972746 -17.26160792 -11.93483089
  -7.90332553  -6.57628696  -8.52624855  -9.24154181 -13.90543509
  -9.13688586  -1.97138856  -6.97191302  -9.53865835 -11.38146078
  -4.80851075  -7.56058687  -7.90930035  -6.89194721 -10.77234875
  -4.89405015  -3.87339359  -5.22790695  -6.71509661  -5.74300737
  -3.5098531   -7.76540232  -2.8924088   -1.19563248  -6.38721232
  -1.37455

In [19]:
days = np.arange(365)
temp = 4 + 20*np.sin(2*np.pi*(days - 100)/365) + np.random.normal(0, 3, 365)

freezing = temp < 0
print(freezing.sum())           # how many freezing days? (True counts as 1!)
print(temp[freezing].mean())    # mean temp on freezing days
print(days[temp > 25])          # which days were hot?

156
-10.716967771598558
[161 173 176 179 184 186 188 190 193 194 195 199 204 207 220 232]


## Some frequently used arrays

* `zeros`: arrays full of 0s
*  `ones`: array full of 1s
*  `empty`: empty array (useful since ndarrays cannot be extended)
*  `arange`: arrays with a range of numbers. Unlike `range`, elements do not have to be integers
*  `linspace`: arrays with equally spaced elements
*  `eye`: 2D identity matrix

In [26]:
L = np.arange(1,5,2)
print(L)

print(np.linspace(0,1,5))


print(np.zeros((3,2), dtype = int))

print(np.ones((3,2)))

print(np.eye(4))


[1 3]
[0.   0.25 0.5  0.75 1.  ]
[[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
            Reference object to allow the creation of arrays which are not
            NumPy arrays. If an array-like passed in as ``like`` supports
  

In [29]:
A = np.array([1,2,3], dtype = float)
print(A)

[1. 2. 3.]


In [30]:
def f(x: float ) -> float:
    return x**2 + 1

# Computing f(x) at 11 equidistributed points between 2 and 5 
print(np.linspace(2, 4, 11))
print(f(np.linspace(2, 4, 11)))    

[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4. ]
[ 5.    5.84  6.76  7.76  8.84 10.   11.24 12.56 13.96 15.44 17.  ]


In [31]:
print(np.zeros( (2,3) ))
print(np.empty( (3,3) )) # values are uninitialized and can be anything

[[0. 0. 0.]
 [0. 0. 0.]]
[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


## Iterating over np.arrays

Consider a np.array of unknown shape. How do we cycle through all entries? The total number of nested foor loops will depend on the shape of the array.

In [32]:
A1 = np.array([1, 2, 3])
A2 = np.array([[1, 2, 3], [4, 5, 6]])
A3 = np.array([[[1, 2, 3], [4, 5, 6]],
              [[-1, -2, -3], [-4, -5, -6]],
              [[10, 20, 30], [40, 50, 60]]])
print(A1)
print(A2)
print(A3)



[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]

 [[10 20 30]
  [40 50 60]]]


In [33]:
for a in A1:
    print('A1: ', a)

A1:  1
A1:  2
A1:  3


In [34]:
for row in A2:
    for a in row:
        print('A2: ', a)

A2:  1
A2:  2
A2:  3
A2:  4
A2:  5
A2:  6


In [35]:
for face in A3:
    for row in face:
        for a in row:
            print('A3: ', a)

A3:  1
A3:  2
A3:  3
A3:  4
A3:  5
A3:  6
A3:  -1
A3:  -2
A3:  -3
A3:  -4
A3:  -5
A3:  -6
A3:  10
A3:  20
A3:  30
A3:  40
A3:  50
A3:  60


numpy provides a nd iterator which will work in all cases:

In [36]:
for a in np.nditer(A1):
    print('A1: ', a)

A1:  1
A1:  2
A1:  3


In [37]:
for a in np.nditer(A2):
    print('A2: ', a)

A2:  1
A2:  2
A2:  3
A2:  4
A2:  5
A2:  6


In [38]:
for a in np.nditer(A3):
    print('A3: ', a)

A3:  1
A3:  2
A3:  3
A3:  4
A3:  5
A3:  6
A3:  -1
A3:  -2
A3:  -3
A3:  -4
A3:  -5
A3:  -6
A3:  10
A3:  20
A3:  30
A3:  40
A3:  50
A3:  60


In [39]:
# Example: compute the L^p norm of a np.array:
def Lpnorm(A, p) -> float:
    norm = 0
    for a in np.nditer(A):
        norm += a**p
    return np.sqrt(norm)

print(Lpnorm(A1, 2))
print(Lpnorm(A2, 2))
print(Lpnorm(A3, 2))

3.7416573867739413
9.539392014169456
96.34313675607619


Similarly, there is a `np.ndenumerate`

In [40]:
for i,a in enumerate(A1):
    print(f'A1[{i}]  {a} ')

for i,row in enumerate(A2):
    for j, a in enumerate(row):
        print(f'A2[{i},{j}] = {a} ')


A1[0]  1 
A1[1]  2 
A1[2]  3 
A2[0,0] = 1 
A2[0,1] = 2 
A2[0,2] = 3 
A2[1,0] = 4 
A2[1,1] = 5 
A2[1,2] = 6 


In [41]:
for i, a in np.ndenumerate(A1):
    print(f'A1[{i}]  {a} ')

for i, a in np.ndenumerate(A2):
    print(f'A2[{i}]  {a} ')

for i, a in np.ndenumerate(A3):
    print(f'A3[{i}]  {a} ')

for i in np.nditer(A):
    print(i)

A1[(0,)]  1 
A1[(1,)]  2 
A1[(2,)]  3 
A2[(0, 0)]  1 
A2[(0, 1)]  2 
A2[(0, 2)]  3 
A2[(1, 0)]  4 
A2[(1, 1)]  5 
A2[(1, 2)]  6 
A3[(0, 0, 0)]  1 
A3[(0, 0, 1)]  2 
A3[(0, 0, 2)]  3 
A3[(0, 1, 0)]  4 
A3[(0, 1, 1)]  5 
A3[(0, 1, 2)]  6 
A3[(1, 0, 0)]  -1 
A3[(1, 0, 1)]  -2 
A3[(1, 0, 2)]  -3 
A3[(1, 1, 0)]  -4 
A3[(1, 1, 1)]  -5 
A3[(1, 1, 2)]  -6 
A3[(2, 0, 0)]  10 
A3[(2, 0, 1)]  20 
A3[(2, 0, 2)]  30 
A3[(2, 1, 0)]  40 
A3[(2, 1, 1)]  50 
A3[(2, 1, 2)]  60 
1.0
2.0
3.0


### Application: applying a function to a ndarray
We saw that numpy tries to do all operations component-wise. Given the 3d array `A3` and a function `f`, we can apply `f` to each term of `A3`: 

In [42]:
def f(x: float) -> float:
    return 2*x
print('f(A1):\n',f(A1))
print('f(A2):\n',f(A2))
print('f(A3):\n',f(A3))


f(A1):
 [2 4 6]
f(A2):
 [[ 2  4  6]
 [ 8 10 12]]
f(A3):
 [[[  2   4   6]
  [  8  10  12]]

 [[ -2  -4  -6]
  [ -8 -10 -12]]

 [[ 20  40  60]
  [ 80 100 120]]]


Sometimes, python needs help, though...

In [43]:
A = np.array([0,-1,2,3,4])
print(A < 0 )

[False  True False False False]


In [44]:
def g(x:float)-> float:
    if x < 0:
        return -x
    else: 
        return x
g(A1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

What happens here is that python substitute `A3` for `x` in `g`, and the statement `if A3 < 0:` is ambiguous.
We could create a *vectorized* version of `g`, but unless we are extra careful, it is no longer going to work for floats...

In [45]:
def gVect(x):
    res = np.empty(x.shape)
    for i, val in np.ndenumerate(x):
        res[i] = g(val)
    return res
print('gVec(A1):\n',gVect(A1))
print('gVec(A1):\n',gVect(A2))
print('gVec(A1):\n',gVect(A3))

# print('gVect(-1):', gVect(-1))

gVec(A1):
 [1. 2. 3.]
gVec(A1):
 [[1. 2. 3.]
 [4. 5. 6.]]
gVec(A1):
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[10. 20. 30.]
  [40. 50. 60.]]]


In [47]:
gVect2 = np.vectorize(g)
print('gVec(2A1):\n',gVect2(A1))
print('gVec(2A1):\n',gVect2(A2))
print('gVec(2A1):\n',gVect2(A3))

print('gVect2(-1):', gVect2(-1))

gVec(2A1):
 [1 2 3]
gVec(2A1):
 [[1 2 3]
 [4 5 6]]
gVec(2A1):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
gVect2(-1): 1


### Exercise

To test our array based thinking, let's try to do the following exercise without loops.

Consider the following array representing dice rolls.

In [15]:
import numpy as np

In [48]:
rolls = np.array([3,6,6,1,6,6,6,2,3,4,5,6,6,6,6,1,1,1,2])

How many times does a $6$ come immediately after another $6$?

First, lets use classic iteration.

In [ ]:
List_rolls = [3,6,6,1,6,6,6,2,3,4,5,6,6,6,6,1,1,1,2]

In [51]:
n = len(List_rolls)
six_ctr = 0

for i in range(1,n):
    if List_rolls[i] == List_rolls[i-1] and List_rolls[i] == 6:
        six_ctr +=1
print(six_ctr)

6


Consider the following to subarrays

In [52]:
print(rolls[:-1])
print(rolls[1:])

[3 6 6 1 6 6 6 2 3 4 5 6 6 6 6 1 1 1]
[6 6 1 6 6 6 2 3 4 5 6 6 6 6 1 1 1 2]


How can we use this observation in order to solve our problem?

In [55]:
print(((rolls[:-1] == 6) & (rolls[1:] == 6)).sum())

6
